CHANNEL_SECRET=''
CHANNEL_TOKEN=''
MODEL_API_TOKEN='api_FaTThXjiOcMNrzITNPyQCjxgZhTsNEgjpB'
DIALO_API_URL='https://api-inference.huggingface.co/models/microsoft/DialoGPT-large'
MODEL_API_URL='https://api-inference.huggingface.co/models/gpt2-xl'
